mojaloop/central-services-shared

- .env
- package.json
- src/logger.js
- test/logger.test.js
Added capability to change the logging level
Updated the tests cases
Anded a .env file
Changes for story: https://github.com/mojaloop/project/issues/161
> Updated Logging feature

- .gitignore
- package-lock.json
- package.json
- src/logger.js
- test/logger.test.js
Impossible to cover `else path not taken`, which results in test-coverage failure.
> feature/648 NodeJs runtime from 8.4.x to 10.15.x LTS

- package.json
- src/healthCheck/HealthCheckEnums.js
As suggested by @rmothilal in the other health check PRs.
> Add responseCode enum and smtpServer service name to enums

- package-lock.json
- package.json
- src/logger.js
This enables string interpolation in log messages.
See [Issue #843](https://github.com/mojaloop/project/issues/843) for more details
> Added splat to winston logger config to enable string interpolation

- .gitignore
- package-lock.json
- package.json
- src/util/endpoints.js
- src/util/hapi/plugins/rawPayloadToDataUri.js
- src/util/headers/transformer.js
- src/util/kafka/consumer.js
- src/util/kafka/index.js
- src/util/kafka/producer.js
- test/unit/util/kafka/producer.test.js
-update existing error handling with FSPIOPError framework
-update unit tests as required by update to existing error handling with FSPIOPError framework
-update package.json dependencies and scripts
-remove package-lock.json from .gitignore
> 915-ApplyFSPIOPErroHandlingFramework

- package-lock.json
- package.json
- src/util/hapi/index.js
- src/util/hapi/plugins/headerValidation.js
- src/util/headerValidation/.gitignore
- src/util/headerValidation/index.js
- test/unit/util/hapi/plugins/headerValidation.test.js
- test/unit/util/headerValidation/support.js
- test/unit/util/headerValidation/validation.test.js
See: https://github.com/mojaloop/account-lookup-service/pull/41#discussion_r318604095 and the enclosing PR for motivation and some context (I expect readers of this PR are familiar, hence my lazy non-reproduction here).
Notes:
- Haven't written a test for the plugin (but have tested it!). I intend to, but it's near the end of my day now- so don't merge this until I have.
- Similarly, I'll address other test coverage tomorrow
- Basically, I expect some feedback on a few things, so I'm seeking it now
> Added header validation library

- README.md
- package-lock.json
- package.json
- src/util/request.js
This allows consumers of this module to take action depending on the failure mode of the request.
> Return HTTP request responses

- src/enums/events.js
- src/enums/kafka.js
Extended ENUMS:
- Event.ActionLetter
- Kafka.TopicMap
> Feature/967 Duplicate checking on bulk services

- package-lock.json
- package.json
- src/enums/endpoints.js
- Add `TRANSFERS_POST`, `TRANSFERS_PUT`, and `TRANSFERS_PUT_ERROR` endpoint templates.
> Add TRANSFERS endpoint templates

- package-lock.json
- package.json
- src/enums/endpoints.js
The following endpoint templates were added:
- BULK_TRANSFERS_POST
- BULK_TRANSFERS_PUT
- BULK_TRANSFERS_PUT_ERROR
> Add endpoint templates for bulk transfers.

- package-lock.json
- package.json
- src/enums/endpoints.js
- Added missing slash to URLs for conformity
> Fix endpoint templates

- package-lock.json
- package.json
- src/enums/endpoints.js
- src/util/eventFramework/index.js
- src/util/eventFramework/tags.js
- src/util/index.js
- test/unit/util/eventFramework/tags.test.js
added helper function to set span tags.
> added getSpanTags method

- package-lock.json
- package.json
> hotfix/v8.6.1 Release Prep

- package-lock.json
- package.json
- src/enums/settlements.js
Implemented changes as per PR Comments : https://github.com/mojaloop/central-ledger/pull/588
- Added new enums
> Feature/1207 Implement settlement models management get and put operations

- package-lock.json
- package.json
- src/enums/settlements.js
- src/util/index.js
- src/util/settlement.js
- test/unit/encoding.test.js
- test/unit/healthCheck/HealthCheck.test.js
- test/unit/index.test.js
- test/unit/util/eventFramework/tags.test.js
- test/unit/util/hapi/plugins/eventPlugin.test.js
- test/unit/util/hapi/plugins/eventPluginIsolated.test.js
- test/unit/util/hapi/plugins/headerValidation.test.js
- test/unit/util/hapi/plugins/rawPayloadToDataUri.test.js
- test/unit/util/hash.test.js
- test/unit/util/index.test.js
- test/unit/util/settlement.test.js
- test/unit/util/streaming/protocol/index.test.js
- settlement model matrix for valid config
- settlement model validation function
- unit tests for new functionality
- sandbox for all unit tests
- license info added
- dependencies update
> feature/1210 Validate settlement model definition

- audit-resolve.json
- package-lock.json
- package.json
- src/enums/events.js
- Added TRANSACTION_REQUEST and AUTHORIZATION event types
- Updated dependencies
- Removed unused dependencies
> #828: Support for Transaction Request Service

- package-lock.json
- package.json
- src/enums/kafka.js
- src/util/request.js
updated dependencies
fix for sendrequest not returning the status on an error
fix for invalid kafka config added
> fixes for central-services issues

- audit-resolve.json
- package-lock.json
- package.json
- src/util/hapi/plugins/headerValidation.js
updated audit-resolve
updated headerValidation event
> fix for header validation at incorrect stage of hapi lifecycle

- package-lock.json
- package.json
- src/util/hapi/plugins/headerValidation.js
- Add 'authorization' to known resources for header validation
> #1285: Update for TRS authorization

- audit-resolve.json
- package-lock.json
- package.json
- src/enums/kafka.js
- Added distinct mapping for 'timeout-reserved' action so that 'timeout-reserved' action is mapped to the notification event topic and handled specifically in ml-api-adapter.
> #1381: Add Kafka topic mapping for 'timeout-reserved' action

- package-lock.json
- package.json
- src/enums/events.js
- Added 'bulkAbort' ActionLetter
> #1423: Bulk transfers error processing

- package-lock.json
- package.json
- src/util/hapi/plugins/headerValidation.js
- src/util/headerValidation/index.js
1. Added supported version 1.1
2. Added supported versions extensions map list and added where error is thrown
3. Incremented project version to 10.4.4
> Changes for bug https://github.com/mojaloop/project/issues/1378

- package-lock.json
- package.json
- src/enums/transfers.js
- src/index.d.ts
feat(mojaloop/#2801): add ABORTING bulk transfer state - [https://github.com/mojaloop/project/issues/2801](https://github.com/mojaloop/project/issues/2801)
- Add ABORTING enum for `BulkTransferState` and `BulkProcessingState`
> feat(mojaloop/#2801): add ABORTING bulk transfer state

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
docs(mojaloop/#3452): update readme
- updated audit section of the readme
- updated dependencies
> docs(mojaloop/#3452): update readme

- package-lock.json
- package.json
- src/enums/endpoints.js
- src/index.d.ts
- src/util/endpoints.js
- src/util/index.js
- src/util/participants.js
- src/util/request.js
- test/unit/util/endpoints.test.js
- test/unit/util/participants.test.js
- test/util/helper.js
feat(mojaloop/#3426): add participant request caching, axios override and metrics
> feat(mojaloop/#3426): add participant request caching, axios override and metrics

- package-lock.json
- package.json
-fix vulnerability
-update dependencies
-replace source code headers to Mojaloop Foundation
> chore: maintenance updates
